### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Moisan** [stacklok/frizbee#175]
### Describe the issue

frizbee fails to pin the version of the `ruby/setup-ruby` action when the version is `setup-ruby@v1`.

### To Reproduce

* Download the following github action file: `wget https://raw.githubusercontent.com/Homebrew/ci-orchestrator/e791dc96262bfd324d1e5238f428e68d2ef7ecca/.github/workflows/main.yml`
* `frizbee actions main.yml`

Note that no update is done. I would expect to see a change from `setup-ruby@v1` to something like 
```
ruby/setup-ruby@161cd54b698f1fb3ea539faab2e036d409550e3c # v1.187.0
```

### What version are you using?

0.0.20

**Comment by rdimitrov** [comment]
hey, @Moisan, thanks for raising this issue. I can confirm that I tried the steps you provided and I was able to reproduce it locally 👍

**Comment by jhrozek** [comment]
The issue is that `ruby/setup-ruby@v1` is a branch, not a tag. By default, frizbee won't pin branches because the assumption we made is that if you use a branch, typically you want to follow the branch (a typical example is `myaction@master`).

This is configurable, e.g. with a config like this:
```
ghactions:
  exclude_branches:
    - main
    - master
  exclude:
    # Exclude the SLSA GitHub Generator workflow.
    # See https://github.com/slsa-framework/slsa-github-generator/issues/2993
    - slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
```
stored in `.frizbee.yml` the action can be resolved:
```
frizbee actions ruby/setup-ruby@v1
ruby/setup-ruby@161cd54b698f1fb3ea539faab2e036d409550e3c
```

I am not sure if dependabot would update the action though, this needs some more testing.
